install:
	mkdir -p ~/.vim/syntax
	mkdir -p ~/.vim/ftdetect
	mkdir -p ~/.vim/ftplugin
	cp syntax/singularity.vim ~/.vim/syntax/
	cp ftdetect/singularity.vim ~/.vim/ftdetect/
	cp ftplugin/singularity.vim ~/.vim/ftplugin/

uninstall:
	rm ~/.vim/syntax/singularity.vim
	rm ~/.vim/ftdetect/singularity.vim
	rm ~/.vim/ftlugin/singularity.vim
	rmdir ~/.vim/syntax
	rmdir ~/.vim/ftdetect
	rmdir ~/.vim/ftplugin
